language: elixir
matrix:
  # https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Compatibility%20and%20Deprecations.md

  - elixir: 1.10
    otp_release: 22.2

env:
  - MIX_ENV=test COVERALLS_ELIXIR_VERSION=1.10 COVERALLS_OTP_RELEASE=22.2 DIALYZER_PLT_FILE=priv/plts/dialyzer.plt
script:
  - make ci
after_script:
  - ./coveralls.sh

cache:
  directories:
    - priv/plts
